title: "INFOPREPA - Cours préparatoires en Informatique "
email: snail.info@unamur.be
description: >- # this means to ignore newlines until "baseurl:"
  Ce site contient le matériel pédagogique des cours préparatoires en informatique de l'Université de Namur.
baseurl: "/INFOPREPA" # the subpath of your site, e.g. /blog
url: "https://snail-unamur.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  snail-unamur

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: GFM # Use the GitHub Flavoured Markdown processor (https://github.github.com/gfm/)
navigation: 0

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
